[package]
name = "ssh2-test"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
description.workspace = true

[dependencies]
anyhow = { workspace = true }
ssh2 = { workspace = true }
